name: Joss Paper Draft

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Joss Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: docs/joss/paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: docs/joss/paper.pdf